" ===============================================
" Vim Config
" Andy Hutchins
" Modified 10-08-2013
" ===============================================

" Set Vim to not be compatible with vi. This is better.
set nocompatible

" Sets the default color scheme and color format
set t_Co=256
colorscheme xoria256

" Set Vim to use BASH isntead of ZSH
set shell=/bin/bash

" Set leader to ,
let mapleader = ","

" Set highlight style
highlight Search cterm=underline

" Open splits
nmap vs :vsplit<cr>
nmap hs :hsplit<cr>

"Resize vsplit
nmap <C-v> :vertical resize +5<cr>
nmap 25 :vertical resize 40<cr>
nmap 50 <c-w>=
nmap 75 :vertical resize 120<cr>

"Load the current buffer in Chrome
nmap ,c :!open -a Google\ Chrome<cr>

" Create/edit file in the current directory
nmap :ed :edit %:p:h/

" Swap files out of the project root
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//

set autowrite  "Save on buffer switch
set mouse=a " Allow mouse scroll



" Fire up pathogen and file indentation
" call pathogen#infect("~/dotfiles/vim/bundles")
filetype plugin indent on

" Turns on syntax higlighting
syntax on
syntax enable

" Turns on line numbers
set number

" Highlight current line
set cursorline

" Down is really the next line
nnoremap j gj
nnoremap k gk

" Supposed to set linebreaks on spaces and not break words across lines
set linebreak

" Sets antialiasing on by default
set antialias

" Ever notice a slight lag after typing the leader key + command? This lowers the timeout.
set timeoutlen=500

" Text stuff
set tabstop=4
set softtabstop=4
set shiftwidth=4
set linespace=15set 
set nowrap
set guifont=essentialpragmatapro:h16
set smartindent
set smarttab
" set copyindent                  " copy the previous indentation on autoindenting
" set autoindent
set expandtab
set visualbell           " don't beep
set noerrorbells         " don't beep
set autoread


"Auto change directory to match current file ,cd
nnoremap ,cd :cd %:p:h<CR>:pwd<CR>

"Searching
set hlsearch
set incsearch
set ignorecase
set smartcase


"Show (partial) command in the status line
set showcmd

" Quickly go forward or backward to buffer
nmap :bp :BufSurfBack<cr>
nmap :bn :BufSurfForward<cr>

" Powerline (Fancy thingy at bottom stuff)
let g:Powerline_symbols = 'fancy'
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)

"==================================================
" => Keyboard Mappings
"==================================================

" Ctrl-n or :H will disable search highlighting
nmap <silent> <C-n> :noh<CR>
command! H let @/=""

" Toggle trailing spaces and tabs
set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>

" Fast saving
nmap <leader>w :w!<cr>

" Fast editing of the .vimrc
map <leader>v :e! ~/.vimrc<cr>

" When vimrc is edited, reload it automatically
autocmd! bufwritepost vimrc source ~/.vimrc

" Auto-remove trailing spaces from PHP files
autocmd BufWritePre *.php :%s/\s\+$//e


" Laravel framework commons
nmap <leader>lr :e app/routes.php<cr>
nmap <leader>lca :e app/config/app.php<cr>81Gf(%O
nmap <leader>lcd :e app/config/database.php<cr>
nmap <leader>lc :e composer.json<cr>

" Fuzzy Finder
nmap <leader>ff :FufFile<cr>
nmap <leader>fb :FufBuffer<cr>


"==================================================
" => GUI Configuration
"==================================================
" Set Vim to always show the position of the cursor on the bottom right corner
set ruler
" Allow persistant background buffers w/o disk-write
set hidden
" Status Bar
set laststatus=2
" Omnicomplete Setup
set wildmenu
set wildmode=list:longest,list:full
" 3 line buffer at window edges
set scrolloff=3
" Remove MacVim menu and toolbar and scrollbars
set guioptions-=T " Remove MacVim toolbar
set guioptions-=L " Remove Left scroll bar
set guioptions-=r " Remove right scrollbars
set guioptions+=a " Autoselect. Visual mode selections available outside MacVim
set guioptions+=c " Use console for simple alerts instead of GUI popup
:set guitablabel=%N\ %f " Set tab label to Tab # and buffer

" Put Vim backup files somewhere else
set backupdir=~/.vim/tmp,~/.tmp,~/tmp,~/var/tmp,/tmp
set directory=~/.vim/tmp,~/.tmp,~/tmp,~/var/tmp,/tmp

" Increase scrolling to 3 lines at a time
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

set cmdheight=1 " Set command lines count
set cmdwinheight=1 " Set command window height
" File edited outside Vim auto-refresh in Vim
set autoread

" Map jj to <esc>
inoremap jj <esc>

" Disable blinking cursor
" set gcr=n:blinkon0

" This should set the window to open maximized.
if has("gui_running")
  " GUI is running or is about to start.
  " Maximize gvim window.
  set lines=999 columns=999
endif

" Open nerdtree
nmap <C-b> :NERDTreeToggle<cr>

" Longer history
set history=1000

" Turn on visual bell, No beeping :)
set visualbell

"The commandbar height
set cmdheight=1

"Ignore case when searching
set ignorecase

"Set magic on, for regular expressions
set magic
"Show matching brackets when text indicator is over them
set showmatch

" Easier window navigation
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Set F5 to pop up quick buffer browser
:nnoremap <F5> :buffers<CR>:buffer<Space>

"========================================
" Custom Functions
"========================================

" Prepare a new PHP class
"function! Class()
"    let name = input('Class name? ')
"    let namespace = input('Any Namespace? ')
"
"    if strlen(namespace)
"        exec 'normal i<?php namespace ' . namespace . ';'
"    else
"        exec 'normal i<?php
"    endif
"
"    " Open class
"    exec 'normal iclass ' . name . ' {^M}^[O^['
"
"    exec 'normal i^M    public function __construct()^M{^M ^M}^['
"endfunction
"nmap ,1  :call Class()<cr>
