# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# install  colordiff package :)
alias diff='colordiff'

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="cloud"

#####################################
#######         Alias'      #########
#####################################
# ZSH
alias zshconfig="mvim ~/.zshrc"
alias ohmyzsh="mvim ~/.oh-my-zsh"

#General
alias mamp="open /Applications/MAMP/MAMP.app" # Start MAMP
alias ss='python -m SimpleHTTPServer' # Start simple server in pwd


# Misccelanneous Helpers
alias cd..='cd ..'
alias c='clear'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias ports='netstat -tulanp'


# get web server headers #
alias header='curl -I'
# find out if remote server supports gzip / mod_deflate or not #
alias headerc='curl -I --compress'

# Safety nets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Web server controlls
# also pass it via sudo so whoever is admin can reload it without calling you #
alias nginxreload='sudo /usr/local/nginx/sbin/nginx -s reload'
alias nginxtest='sudo /usr/local/nginx/sbin/nginx -t'
alias lightyload='sudo /etc/init.d/lighttpd reload'
alias lightytest='sudo /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -t'
alias httpdreload='sudo /usr/sbin/apachectl -k graceful'
alias httpdtest='sudo /usr/sbin/apachectl -t && /usr/sbin/apachectl -t -D DUMP_VHOSTS'

# System Info
## pass options to free ##
alias meminfo='free -m -l -t'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## Get server cpu info ##
alias cpuinfo='lscpu'

## older system use /proc/cpuinfo ##
##alias cpuinfo='less /proc/cpuinfo' ##

## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

# Set Vim helpers
alias vi=vim
alias svi='sudo vi'
alias vis='vim "+set si"'
alias edit='vim'


# GREP
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias mkdir='mkdir -pv'






# Logs
alias phplog="tail -f /Applications/MAMP/logs/php_error.log"
alias apachelog="tail -f /Applications/MAMP/logs/apache_error.log"
alias mysqllog="tail -f /Applications/MAMP/logs/mysql_error_log.err"

# Shortcut Alias'
alias active="cd /Users/903364/Projects/ACTIVE"
alias ls="-al --color=auto"
alias chrome="open /Applications/Google\ Chrome.app"
alias dfvim="cd ~/dotfiles/vim"

# VimRC Edit
alias vimrc='mvim ~/dotfiles/vim/vimrc'

# Git Alias
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias hist='hist = log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short'

alias gpom='git push origin master'

# Alias common GIT misspellings
alias got='git '
alias get='git '

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn)

# Set zsh source
source $ZSH/oh-my-zsh.sh

# Setup paths
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/X11/bin:/Users/903364/bin
export EDITOR='/Users/903364/bin/vim'
export PATH=/Applications/MAMP/bin/php/php5.3.6/bin:$PATH
