# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="cloud"

#####################################
#######         Alias'      #########
#####################################
# ZSH
alias zshconfig="mvim ~/.zshrc"
alias ohmyzsh="mvim ~/.oh-my-zsh"
#General
alias ss="python -m SimpleHTTPServer" # Start python server 
alias mamp="open /Applications/MAMP/MAMP.app" # Start MAMP
alias ls='ls -a'
alias ra='rails'
alias rb='ruby'
alias ss='python -m SimpleHTTPServer' # Start simple server in pwd


# Logs
alias phplog="tail -f /Applications/MAMP/logs/php_error.log"
alias apachelog="tail -f /Applications/MAMP/logs/apache_error.log"
alias mysqllog="tail -f /Applications/MAMP/logs/mysql_error_log.err"

# Shortcut Alias'
alias active="cd /Users/903364/Projects/ACTIVE"
alias ls="lsa -al"
alias chrome="open /Applications/Google\ Chrome.app"
alias dfvim="cd ~/dotfiles/vim"

# VimRC Edit
alias vimrc='mvim ~/dotfiles/vim/vimrc'

# Git Alias
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias hist='hist = log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short'

alias gpom='git push origin master'

# Alias common GIT misspellings
alias got='git '
alias get='git '

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn)

# Set zsh source
source $ZSH/oh-my-zsh.sh

# Setup paths
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/X11/bin:/Users/903364/bin
export EDITOR='/Users/903364/bin/vim'
export PATH=/Applications/MAMP/bin/php/php5.3.6/bin:$PATH
